export const firstQueuePlots = [
  { number: 30, house: "L", area: 14.72, price: null, status: "Продан" },
  { number: 29, house: "L", area: 15, price: null, status: "Продан" },
  { number: 28, house: "L", area: 10.91, price: 10.5, status: "Свободен" },
  { number: 27, house: "M", area: 11.32, price: null, status: "Продан" },
  { number: 26, house: "L", area: 12.15, price: 10.7, status: "Свободен" },
  { number: 25, house: "M", area: 12.75, price: 9.5, status: "Свободен" },
  { number: 24, house: "M", area: 12.23, price: 9.5, status: "Свободен" },
  { number: 23, house: "L", area: 12.75, price: null, status: "Продан" },
  { number: 21, house: "S", area: 6.41, price: null, status: "Продан" },
  { number: 20, house: "M", area: 6.27, price: 8.4, status: "Забронирован" },
  { number: 19, house: "S", area: 6.23, price: 6.9, status: "Свободен" },
  { number: 18, house: "M", area: 6.31, price: 8.4, status: "Свободен" },
  { number: 17, house: "S", area: 6.31, price: 6.9, status: "Свободен" },
  { number: 16, house: "S", area: 6.03, price: 6.9, status: "Забронирован" },
  { number: 60, house: "S", area: 6.54, price: 7.6, status: "Свободен" },
  { number: 59, house: "M", area: 8.39, price: 9, status: "Свободен" },
  { number: 58, house: "L", area: 8.4, price: 10, status: "Свободен" },
];
